name: Flutter Build CI
on:
  push:
    paths:
      - '.github/workflows/**'
  pull_request:
    branches:
      - dev
      - master
    paths:
      - '.github/workflows/**'
      - 'pubspec.yaml'
      - 'pubspec.lock'
      - 'lib/**'
      - 'ios/**'
      - 'android/**'
jobs:
  # Limits push tp Master branch
  limit_master_pr:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Limit PR to master from any branch
    steps:
      - uses: LukBukkit/action-pr-limits@v1
        with:
          whitelist: |
            dev

### Runs Flutter Test
  # Assumes you ahve tests in your app. If no test the build will fail.
  # IF no tests, Just remove this block of flutter test and also the
  #  subsequent lines   needs: [flutter_test] in the various build jobs
  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    # Declare environment variables that you wnat the actions to run against.
    env:
      JAVA_VERSION: "11.0"
      FLUTTER_VERSION: "2.0.0"
      CHANNEL: "beta"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: $
      - uses: subosito/flutter-action@v1
        with:
          # You can also explicitly declare the flutter ve=wersion you want to run your CI on by
          # replacing channel with:
          # flutter_version:$

          channel: $
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test

# We run the tests first and wait for thyem to pass.
#  Should the tests fail, they will abandon the proceeding actions


  ### Builds Android App bundles instead of apk
  build_appbundle:
    name: Build Flutter (Android)
    needs: [flutter_test]
 # Checks whether tests passed before proceeding.
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: "11.0"
      FLUTTER_VERSION: "2.0.0"
      CHANNEL: "beta"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: $
      - uses: subosito/flutter-action@v1
        with:
          channel: $
      - run: echo "::add-path::$GITHUB_WORKSPACE/_flutter/bin"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build appbundle
        working-directory: ./

  ### BUilds IOS ia
  build_ios:
    name: Build Flutter (iOS)
    needs: [ flutter_test ]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "beta"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build ios --release --no-codesign

  ### Builds web
  buildweb:
    name: Build Web
    needs: [flutter_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: "beta"
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build web
